application: html5-canvas
version: 1
runtime: python
api_version: 1

#default_expiration: "30d"

handlers:

- url: (.*)/
  static_files: web-site\1/index.html
  upload: web-site/index.html

- url: /
  static_dir: web-site
  
